#!/bin/bash

#xcode-select -p
xcode-select --install

#which sigh
if [ ! -f "/usr/local/bin/sigh" ]; then
    sudo gem install sigh
fi

if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME     
    _java="$JAVA_HOME/bin/java"
else
    echo "no java"
fi
if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"
    if [[ "$version" > "1.8" ]]; then
        echo 'version is more than 1.8'
    else         
        echo 'version is less than 1.8'
    fi
fi

#su $USER -c 'java -jar /Applications/Scripture\ App\ Builder.app/Contents/Java/bin/scripture-app-builder.jar'

