#!/bin/bash

sudo ln -fs /Library/Frameworks/Python.framework/Versions/2.7/bin/aeneas* /usr/local/bin/
export PATH=/usr/local/bin:/usr/local/sbin:~/bin:$PATH

if [ ! -n "$(grep 'export PATH=/usr/local/bin:/usr/local/sbin:~/bin:$PATH' ~/.bash_profile)" ]; then
	touch $HOME/.bash_profile
	echo 'export PATH=/usr/local/bin:/usr/local/sbin:~/bin:$PATH' >> $HOME/.bash_profile
	chown $USER $HOME/.bash_profile
fi

osascript <<END 
tell application "Terminal"
	do script "aeneas_check_setup; exit"
	activate
end tell
END
