#!/bin/bash

export PATH="@PREFIX@/bin:@PREFIX@/sbin:$PATH"

if [ ! -f $HOME/.bash_profile ]; then
  touch $HOME/.bash_profile
  /bin/chmod 0700 $HOME/.bash_profile
  /usr/sbin/chown $USER $HOME/.bash_profile
  if [ -f $HOME/.profile ]; then
    if [ ! -n "$(/usr/bin/grep '. ~/.profile' $HOME/.bash_profile)" ]; then
      echo '[ -r ~/.profile ] && . ~/.profile' >> $HOME/.bash_profile
    fi
  fi
fi
if [ ! -n "$(/usr/bin/grep '^export PATH="@PREFIX@/bin:@PREFIX@/sbin:' $HOME/.bash_profile)" ]; then
  echo 'export PATH="@PREFIX@/bin:@PREFIX@/sbin:$PATH"' >> $HOME/.bash_profile
fi
if [ ! -f $HOME/.zshenv ]; then
  touch $HOME/.zshenv
  /bin/chmod 0700 $HOME/.zshenv
  /usr/sbin/chown $USER $HOME/.zshenv
fi
if [ ! -n "$(/usr/bin/grep '^export PATH="@PREFIX@/bin:@PREFIX@/sbin:' $HOME/.zshenv)" ]; then
  echo 'export PATH="@PREFIX@/bin:@PREFIX@/sbin:$PATH"' >> $HOME/.zshenv
fi

python3 -m pip install -U @PREFIX@/share/aeneas_tools/aeneas-*.whl

osascript <<END
tell application "Terminal"
        set newTab to do script "aeneas_check_setup; exit"
        activate
        set current settings of newTab to settings set "Pro"
        set theWindow to first window of (every window whose tabs contains newTab)
        set windowId to theWindow's id
        delay 5
        try
                close (every window whose tabs contains newTab)
        end try
end tell
tell application "Installer"
        activate
end tell
END

exit 0
